name: Publish to npm

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  version-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Bump version and create tag
      run: |
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        NEW_VERSION=$(npm version patch | grep 'v' | awk '{print $1}')
        if git tag -l | grep "$NEW_VERSION"; then
          echo "Tag $NEW_VERSION already exists. Skipping tag creation."
          git push origin $NEW_VERSION
        else
          git tag $NEW_VERSION
          git push origin $NEW_VERSION
        fi
      # env:
      #  GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
